import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDown, ArrowLeft, ArrowUp, CheckCircle2, CopyPlus, Download, Eye, FileSpreadsheet, Pencil, Plus, Save, Send, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import type { ReactElement } from "react";
import { Link, useParams } from "react-router-dom";
import { Button } from "../../components/ui/Button";
import { Input } from "../../components/ui/Input";
import { Modal } from "../../components/ui/Modal";
import { Select } from "../../components/ui/Select";
import { TextArea } from "../../components/ui/TextArea";
import { useAuth } from "../../context/AuthContext";
import { apiErrorMessage, formatDate } from "../vacancies/formatters";
import { archiveTemplateVersion, confirmTemplateExcel, createTemplateVersion, downloadTemplateExample, getTemplate, getTemplateVersion, previewTemplateExcel, publishTemplateVersion, saveTemplateContent, updateTemplate } from "./templatesApi";
import { questionTypeLabel, templateStatusLabel, type ExcelPreview, type QuestionType, type TemplateQuestionInput, type TemplateSectionInput } from "./types";

const emptyQuestion = (): TemplateQuestionInput => ({ prompt: "", helpText: "", type: "LONG_TEXT", required: false, weight: null, competency: "", evaluationGuidance: "", configuration: {} });

export function TemplateDetailPage() {
  const { templateId = "" } = useParams();
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const [selectedVersionId, setSelectedVersionId] = useState("");
  const [sections, setSections] = useState<TemplateSectionInput[]>([]);
  const [preview, setPreview] = useState(false);
  const [importPreview, setImportPreview] = useState<ExcelPreview | null>(null);
  const [importOpen, setImportOpen] = useState(false);
  const [metadataOpen, setMetadataOpen] = useState(false);
  const [metadataName, setMetadataName] = useState("");
  const [metadataDescription, setMetadataDescription] = useState("");
  const template = useQuery({ queryKey: ["charlas-template", templateId], queryFn: () => getTemplate(templateId), enabled: Boolean(templateId) });
  useEffect(() => {
    if (!selectedVersionId && template.data?.versions[0]) setSelectedVersionId(template.data.versions[0].id);
  }, [selectedVersionId, template.data]);
  const version = useQuery({ queryKey: ["charlas-template-version", selectedVersionId], queryFn: () => getTemplateVersion(selectedVersionId), enabled: Boolean(selectedVersionId) });
  useEffect(() => {
    if (version.data) setSections((version.data.sections ?? []).map((section) => ({ title: section.title, description: section.description, questions: section.questions.map(stripQuestion) })));
  }, [version.data]);
  const invalidate = () => { queryClient.invalidateQueries({ queryKey: ["charlas-template", templateId] }); queryClient.invalidateQueries({ queryKey: ["charlas-template-version", selectedVersionId] }); queryClient.invalidateQueries({ queryKey: ["charlas-templates"] }); };
  const save = useMutation({ mutationFn: () => saveTemplateContent(selectedVersionId, sections), onSuccess: invalidate });
  const publish = useMutation({ mutationFn: () => publishTemplateVersion(selectedVersionId), onSuccess: invalidate });
  const archive = useMutation({ mutationFn: () => archiveTemplateVersion(selectedVersionId), onSuccess: invalidate });
  const clone = useMutation({ mutationFn: () => createTemplateVersion(templateId, { sourceVersionId: selectedVersionId, changeSummary: `Nueva versión desde v${version.data?.versionNumber}` }), onSuccess: (created) => { invalidate(); setSelectedVersionId(created.id); } });
  const importFile = useMutation({ mutationFn: previewTemplateExcel, onSuccess: setImportPreview });
  const confirmImport = useMutation({ mutationFn: () => confirmTemplateExcel(templateId, importPreview!), onSuccess: (created) => { invalidate(); setSelectedVersionId(created.id); setImportOpen(false); setImportPreview(null); } });
  const metadata = useMutation({ mutationFn: () => updateTemplate(templateId, { name: metadataName, description: metadataDescription }), onSuccess: () => { invalidate(); setMetadataOpen(false); } });
  const canManage = user?.capabilities.includes("template.manage") ?? false;
  const canPublish = user?.capabilities.includes("template.publish") ?? false;
  const isDraft = version.data?.status === "DRAFT";
  const error = save.error ?? publish.error ?? archive.error ?? clone.error ?? confirmImport.error ?? metadata.error;

  if (template.isLoading) return <Notice text="Cargando plantilla…" />;
  if (!template.data || template.isError) return <Notice text={apiErrorMessage(template.error)} error />;

  return <div className="space-y-6">
    <Link to="/charlas/templates" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-emerald-600"><ArrowLeft className="h-4 w-4" /> Volver a plantillas</Link>
    <section className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-600">Editor versionado</p><h1 className="mt-2 text-3xl font-semibold">{template.data.name}</h1><p className="mt-2 text-sm text-slate-500">{template.data.description || "Sin descripción"}</p></div><div className="flex flex-wrap gap-2">{canManage && <Button variant="secondary" onClick={() => { setMetadataName(template.data.name); setMetadataDescription(template.data.description ?? ""); setMetadataOpen(true); }}><Pencil className="h-4 w-4" /> Editar datos</Button>}{canManage && <Button variant="secondary" onClick={() => setImportOpen(true)}><FileSpreadsheet className="h-4 w-4" /> Importar Excel</Button>}<Button variant="secondary" onClick={() => setPreview((value) => !value)}><Eye className="h-4 w-4" /> {preview ? "Editar" : "Previsualizar"}</Button></div></section>

    <section className="grid gap-4 rounded-2xl border app-card-surface p-4 lg:grid-cols-[minmax(240px,1fr)_auto] lg:items-end">
      <Select label="Versión" value={selectedVersionId} onChange={(event) => setSelectedVersionId(event.target.value)} options={template.data.versions.map((item) => ({ value: item.id, label: `Versión ${item.versionNumber} · ${templateStatusLabel[item.status]}` }))} />
      <div className="flex flex-wrap gap-2">{version.data && <span className="self-center rounded-full bg-slate-100 px-3 py-2 text-xs font-semibold dark:bg-white/5">{templateStatusLabel[version.data.status]} {version.data.publishedAt ? `· ${formatDate(version.data.publishedAt)}` : ""}</span>}{canManage && version.data && <Button size="sm" variant="secondary" loading={clone.isPending} onClick={() => clone.mutate()}><CopyPlus className="h-4 w-4" /> Crear nueva versión</Button>}{canPublish && isDraft && <Button size="sm" loading={publish.isPending} onClick={() => window.confirm("La versión publicada quedará inmutable. ¿Continuar?") && publish.mutate()}><Send className="h-4 w-4" /> Publicar</Button>}{canPublish && version.data?.status === "PUBLISHED" && <Button size="sm" variant="secondary" loading={archive.isPending} onClick={() => archive.mutate()}>Archivar</Button>}</div>
    </section>
    {error && <Notice text={apiErrorMessage(error)} error />}

    {version.isLoading ? <Notice text="Cargando contenido…" /> : preview || !isDraft || !canManage ? <TemplatePreview sections={sections} /> : <TemplateEditor sections={sections} onChange={setSections} />}
    {isDraft && canManage && !preview && <div className="sticky bottom-4 flex justify-end"><Button loading={save.isPending} disabled={!sections.length} onClick={() => save.mutate()}><Save className="h-4 w-4" /> Guardar borrador</Button></div>}

    <Modal open={importOpen} onClose={() => setImportOpen(false)} title="Importar plantilla desde Excel" description="El archivo se valida y muestra antes de crear una nueva versión DRAFT. Nunca se publica automáticamente." className="max-w-4xl" footer={<><Button variant="ghost" onClick={() => setImportOpen(false)}>Cerrar</Button>{importPreview?.valid && <Button loading={confirmImport.isPending} onClick={() => confirmImport.mutate()}><CheckCircle2 className="h-4 w-4" /> Confirmar borrador</Button>}</>}>
      <div className="space-y-4"><div className="flex flex-wrap items-center gap-3"><Button variant="secondary" onClick={() => downloadTemplateExample()}><Download className="h-4 w-4" /> Descargar ejemplo</Button><label className="cursor-pointer rounded-xl border border-dashed border-emerald-400 px-4 py-2.5 text-sm font-semibold text-emerald-700 dark:text-emerald-300"><input type="file" accept=".xlsx" className="hidden" onChange={(event) => event.target.files?.[0] && importFile.mutate(event.target.files[0])} />Seleccionar .xlsx</label>{importFile.isPending && <span className="text-sm text-slate-500">Validando…</span>}</div>{importFile.isError && <Notice text={apiErrorMessage(importFile.error)} error />}{importPreview && <div className="rounded-xl border p-4"><p className={`font-semibold ${importPreview.valid ? "text-emerald-600" : "text-rose-600"}`}>{importPreview.valid ? "Archivo válido" : "Se requieren correcciones"} · {importPreview.rowsRead} filas · {importPreview.sections.length} secciones</p>{importPreview.errors.length > 0 && <ul className="mt-3 space-y-1 text-sm text-rose-600">{importPreview.errors.map((item, index) => <li key={`${item.row}-${index}`}>Fila {item.row || "general"}: {item.message}</li>)}</ul>}{importPreview.sections.length > 0 && <div className="mt-4 max-h-80 overflow-y-auto"><TemplatePreview sections={importPreview.sections} compact /></div>}</div>}</div>
    </Modal>
    <Modal open={metadataOpen} onClose={() => setMetadataOpen(false)} title="Datos de la plantilla" description="El nombre y la descripción identifican la plantilla; no alteran el contenido histórico de sus versiones." footer={<><Button variant="ghost" onClick={() => setMetadataOpen(false)}>Cancelar</Button><Button loading={metadata.isPending} disabled={!metadataName.trim()} onClick={() => metadata.mutate()}><Save className="h-4 w-4" /> Guardar</Button></>}>
      <div className="space-y-4"><Input label="Nombre" value={metadataName} onChange={(event) => setMetadataName(event.target.value)} maxLength={180} /><TextArea label="Descripción" value={metadataDescription} onChange={(event) => setMetadataDescription(event.target.value)} rows={4} /></div>
    </Modal>
  </div>;
}

function TemplateEditor({ sections, onChange }: { sections: TemplateSectionInput[]; onChange: (sections: TemplateSectionInput[]) => void }) {
  const updateSection = (index: number, patch: Partial<TemplateSectionInput>) => onChange(sections.map((section, position) => position === index ? { ...section, ...patch } : section));
  const move = (index: number, offset: number) => { const next = [...sections]; const target = index + offset; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; onChange(next); };
  return <div className="space-y-4">{sections.map((section, sectionIndex) => <section key={sectionIndex} className="rounded-2xl border app-card-surface overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 dark:border-white/5 sm:flex-row"><div className="grid flex-1 gap-3 sm:grid-cols-2"><Input label="Sección" value={section.title} onChange={(event) => updateSection(sectionIndex, { title: event.target.value })} /><Input label="Descripción" value={section.description ?? ""} onChange={(event) => updateSection(sectionIndex, { description: event.target.value })} /></div><div className="flex items-end gap-1"><IconButton label="Subir sección" onClick={() => move(sectionIndex, -1)}><ArrowUp /></IconButton><IconButton label="Bajar sección" onClick={() => move(sectionIndex, 1)}><ArrowDown /></IconButton><IconButton label="Eliminar sección" danger onClick={() => onChange(sections.filter((_, index) => index !== sectionIndex))}><Trash2 /></IconButton></div></div><div className="space-y-3 p-4">{section.questions.map((question, questionIndex) => <QuestionEditor key={questionIndex} question={question} onChange={(next) => updateSection(sectionIndex, { questions: section.questions.map((item, index) => index === questionIndex ? next : item) })} onMove={(offset) => { const questions = [...section.questions]; const target = questionIndex + offset; if (target < 0 || target >= questions.length) return; [questions[questionIndex], questions[target]] = [questions[target], questions[questionIndex]]; updateSection(sectionIndex, { questions }); }} onDelete={() => updateSection(sectionIndex, { questions: section.questions.filter((_, index) => index !== questionIndex) })} />)}<Button size="sm" variant="secondary" onClick={() => updateSection(sectionIndex, { questions: [...section.questions, emptyQuestion()] })}><Plus className="h-4 w-4" /> Agregar pregunta</Button></div></section>)}<Button variant="secondary" onClick={() => onChange([...sections, { title: `Nueva sección ${sections.length + 1}`, description: "", questions: [emptyQuestion()] }])}><Plus className="h-4 w-4" /> Agregar sección</Button></div>;
}

function QuestionEditor({ question, onChange, onMove, onDelete }: { key?: number; question: TemplateQuestionInput; onChange: (question: TemplateQuestionInput) => void; onMove: (offset: number) => void; onDelete: () => void }) {
  const configText = question.type === "SINGLE_SELECT" || question.type === "MULTI_SELECT" ? ((question.configuration.options as string[] | undefined) ?? []).join(" | ") : question.type === "SCALE" ? [question.configuration.min ?? 1, question.configuration.max ?? 5, question.configuration.step ?? 1, question.configuration.minLabel ?? "", question.configuration.maxLabel ?? ""].join(" | ") : "";
  const setType = (type: QuestionType) => onChange({ ...question, type, configuration: type === "SINGLE_SELECT" || type === "MULTI_SELECT" ? { options: [] } : type === "SCALE" ? { min: 1, max: 5, step: 1 } : {} });
  const setConfig = (value: string) => { const parts = value.split("|").map((item) => item.trim()); onChange({ ...question, configuration: question.type === "SCALE" ? { min: Number(parts[0] || 1), max: Number(parts[1] || 5), step: Number(parts[2] || 1), minLabel: parts[3] || undefined, maxLabel: parts[4] || undefined } : { options: parts.filter(Boolean) } }); };
  return <div className="rounded-xl border border-slate-200 p-4 dark:border-white/10"><div className="grid gap-3 lg:grid-cols-[1fr_220px_auto]"><TextArea label="Pregunta" value={question.prompt} onChange={(event) => onChange({ ...question, prompt: event.target.value })} rows={2} /><Select label="Tipo" value={question.type} onChange={(event) => setType(event.target.value as QuestionType)} options={Object.entries(questionTypeLabel).map(([value, label]) => ({ value, label }))} /><div className="flex items-end gap-1"><IconButton label="Subir" onClick={() => onMove(-1)}><ArrowUp /></IconButton><IconButton label="Bajar" onClick={() => onMove(1)}><ArrowDown /></IconButton><IconButton label="Eliminar" danger onClick={onDelete}><Trash2 /></IconButton></div></div><div className="mt-3 grid gap-3 md:grid-cols-3"><Input label="Competencia" value={question.competency ?? ""} onChange={(event) => onChange({ ...question, competency: event.target.value })} /><Input label="Peso" type="number" min="0" value={question.weight ?? ""} onChange={(event) => onChange({ ...question, weight: event.target.value === "" ? null : Number(event.target.value) })} /><label className="flex items-end gap-2 pb-3 text-sm"><input type="checkbox" checked={question.required} onChange={(event) => onChange({ ...question, required: event.target.checked })} /> Obligatoria</label></div><div className="mt-3 grid gap-3 md:grid-cols-2"><Input label="Ayuda" value={question.helpText ?? ""} onChange={(event) => onChange({ ...question, helpText: event.target.value })} /><Input label="Guía de evaluación" value={question.evaluationGuidance ?? ""} onChange={(event) => onChange({ ...question, evaluationGuidance: event.target.value })} /></div>{["SINGLE_SELECT", "MULTI_SELECT", "SCALE"].includes(question.type) && <Input className="mt-3" label={question.type === "SCALE" ? "Escala: min | max | paso | etiqueta min | etiqueta max" : "Opciones separadas por |"} value={configText} onChange={(event) => setConfig(event.target.value)} />}</div>;
}

export function TemplatePreview({ sections, compact = false }: { sections: TemplateSectionInput[]; compact?: boolean }) {
  return <div className="space-y-4">{sections.length === 0 && <Notice text="Esta versión todavía no tiene contenido." />}{sections.map((section, sectionIndex) => <section key={sectionIndex} className="rounded-2xl border app-card-surface p-5"><h2 className="font-semibold">{section.title}</h2>{section.description && <p className="mt-1 text-sm text-slate-500">{section.description}</p>}<div className="mt-4 space-y-4">{section.questions.map((question, index) => <div key={index} className="rounded-xl bg-slate-50 p-4 dark:bg-white/[0.035]"><p className="text-sm font-medium">{index + 1}. {question.prompt} {question.required && <span className="text-rose-500">*</span>}</p><p className="mt-1 text-xs text-slate-400">{questionTypeLabel[question.type]}{question.competency ? ` · ${question.competency}` : ""}{question.weight != null ? ` · peso ${question.weight}` : ""}</p>{!compact && <PreviewControl question={question} />}</div>)}</div></section>)}</div>;
}

function PreviewControl({ question }: { question: TemplateQuestionInput }) { if (question.type === "LONG_TEXT") return <textarea disabled className="mt-3 w-full rounded-lg border bg-white p-3 dark:bg-black/10" />; if (question.type === "BOOLEAN") return <div className="mt-3 flex gap-2"><button disabled className="rounded-lg border px-3 py-2">Sí</button><button disabled className="rounded-lg border px-3 py-2">No</button></div>; if (question.type === "SINGLE_SELECT" || question.type === "MULTI_SELECT") return <div className="mt-3 flex flex-wrap gap-2">{((question.configuration.options as string[]) ?? []).map((option) => <span key={option} className="rounded-lg border px-3 py-2 text-xs">{option}</span>)}</div>; return <input disabled className="mt-3 w-full rounded-lg border bg-white p-3 dark:bg-black/10" type={question.type === "NUMBER" || question.type === "SCALE" ? "number" : "text"} />; }
function IconButton({ label, children, onClick, danger = false }: { label: string; children: ReactElement; onClick: () => void; danger?: boolean }) { return <button type="button" title={label} aria-label={label} onClick={onClick} className={`rounded-lg p-2 ${danger ? "text-rose-500 hover:bg-rose-50" : "text-slate-500 hover:bg-slate-100 dark:hover:bg-white/5"}`}>{children}</button>; }
function stripQuestion(question: { prompt: string; helpText?: string | null; type: QuestionType; required: boolean; weight?: number | string | null; competency?: string | null; evaluationGuidance?: string | null; configuration: Record<string, unknown> }): TemplateQuestionInput { return { prompt: question.prompt, helpText: question.helpText, type: question.type, required: question.required, weight: question.weight == null ? null : Number(question.weight), competency: question.competency, evaluationGuidance: question.evaluationGuidance, configuration: question.configuration }; }
function Notice({ text, error = false }: { text: string; error?: boolean }) { return <div className={`rounded-2xl border p-8 text-center text-sm ${error ? "border-rose-200 bg-rose-50 text-rose-700 dark:bg-rose-400/10" : "app-card-surface text-slate-500"}`}>{text}</div>; }
