import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, ArrowLeft, BrainCircuit, CheckCircle2, MessageSquareText, Scale, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Button } from "../../components/ui/Button";
import { Modal } from "../../components/ui/Modal";
import { Select } from "../../components/ui/Select";
import { TextArea } from "../../components/ui/TextArea";
import { apiErrorMessage, formatDate } from "../vacancies/formatters";
import { useAuth } from "../../context/AuthContext";
import { getCandidateIntelligence, requestCandidateAssessment, retryIntelligenceJob, saveSelectionDecision } from "./intelligenceApi";
import { decisionLabel, recommendationLabel, type SelectionDecisionType } from "./types";

export function CandidateIntelligencePage() {
  const { applicationId = "" } = useParams();
  const queryClient = useQueryClient();
  const { user } = useAuth();
  const detail = useQuery({ queryKey: ["charlas-candidate-intelligence", applicationId], queryFn: () => getCandidateIntelligence(applicationId), enabled: Boolean(applicationId), refetchInterval: (query) => ["PENDING", "PROCESSING"].includes(query.state.data?.assessmentJob?.status ?? "") ? 2500 : false });
  const [decisionOpen, setDecisionOpen] = useState(false);
  const [decision, setDecision] = useState<SelectionDecisionType>("ON_HOLD");
  const [reason, setReason] = useState("");
  const [notes, setNotes] = useState("");
  const [acknowledge, setAcknowledge] = useState(false);
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ["charlas-candidate-intelligence", applicationId] }); queryClient.invalidateQueries({ queryKey: ["charlas-intelligence-overview"] }); };
  const regenerate = useMutation({ mutationFn: () => requestCandidateAssessment(applicationId, true), onSuccess: refresh });
  const retryAssessment = useMutation({ mutationFn: retryIntelligenceJob, onSuccess: refresh });
  const saveDecision = useMutation({ mutationFn: () => saveSelectionDecision(applicationId, { decision, reason, notes, assessmentId: detail.data?.assessment?.id, acknowledgeCoreCapacityWarning: acknowledge }), onSuccess: () => { setDecisionOpen(false); refresh(); } });

  if (detail.isLoading) return <Notice text="Cargando assessment del candidato…" />;
  if (!detail.data || detail.isError) return <Notice text={apiErrorMessage(detail.error)} error />;
  const data = detail.data;
  const assessment = data.assessment;
  const output = assessment?.output;
  const error = regenerate.error ?? retryAssessment.error ?? saveDecision.error;

  return <div className="space-y-6">
    <Link to={`/charlas/vacancies/${data.process.vacancyReferenceId}`} className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-emerald-600"><ArrowLeft className="h-4 w-4" /> Volver al proceso</Link>
    <section className="rounded-2xl border app-card-surface p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><p className="text-xs font-bold uppercase tracking-wider text-violet-600">Inteligencia del candidato</p><h1 className="mt-2 text-3xl font-semibold">{data.application.candidate.fullName}</h1><p className="mt-2 text-sm text-slate-500">{data.process.vacancyReference.positionName} · {data.process.vacancyReference.areaName || "Área no informada"}</p><div className="mt-3 flex flex-wrap gap-2"><Badge text={`${data.coverage.completedInterviews}/${data.coverage.requiredInterviews} charlas`} tone={data.coverage.status === "COMPLETE" ? "green" : "amber"} /><Badge text={assessment?.status ?? "SIN ASSESSMENT"} tone={assessment?.status === "COMPLETED" ? "green" : assessment?.status === "FAILED" ? "red" : "amber"} /><Badge text={`Confidence ${assessment?.confidence != null ? `${Math.round(Number(assessment.confidence) * 100)}%` : "N/D"}`} tone="slate" /></div></div><div className="flex flex-wrap gap-2">{assessment?.status === "FAILED" && data.assessmentJob?.status === "FAILED" && user?.capabilities.includes("intelligence.generate") && <Button variant="secondary" loading={retryAssessment.isPending} onClick={() => retryAssessment.mutate(data.assessmentJob!.id)}><BrainCircuit className="h-4 w-4" /> Retry</Button>}{assessment && user?.capabilities.includes("intelligence.regenerate") && <Button variant="secondary" loading={regenerate.isPending} onClick={() => window.confirm("Se creará una nueva versión de assessment y la anterior conservará trazabilidad. ¿Continuar?") && regenerate.mutate()}><BrainCircuit className="h-4 w-4" /> Regenerar</Button>}{data.canManageDecision && <Button onClick={() => { setDecision(data.decision?.decision ?? "ON_HOLD"); setReason(""); setNotes(""); setDecisionOpen(true); }}><Scale className="h-4 w-4" /> {data.decision ? "Cambiar decisión" : "Registrar decisión"}</Button>}</div></div></section>
    {error && <Notice text={apiErrorMessage(error)} error />}

    <section className="grid gap-4 lg:grid-cols-2">
      <div className="rounded-2xl border border-violet-200 bg-violet-50/60 p-5 dark:bg-violet-400/10"><div className="flex items-center gap-2 text-violet-700"><BrainCircuit className="h-5 w-5" /><h2 className="font-semibold">Recomendación IA</h2></div><p className="mt-4 text-lg font-semibold">{assessment ? recommendationLabel[assessment.recommendation] : "No generada"}</p><p className="mt-2 text-sm leading-6 text-slate-600">{output?.recommendationExplanation || "La IA aporta contexto, no decide."}</p><div className="mt-4 rounded-xl bg-white/70 p-3 dark:bg-black/10"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Score explicable</p><p className="mt-1 text-2xl font-semibold">{assessment?.overallScore != null ? `${Number(assessment.overallScore).toFixed(1)} / 100` : "No disponible"}</p><p className="mt-1 text-xs text-slate-500">{assessment?.aggregateScoring?.reason || "Derivado de pesos y criterios configurados."}</p></div></div>
      <div className="rounded-2xl border border-emerald-200 bg-emerald-50/60 p-5 dark:bg-emerald-400/10"><div className="flex items-center gap-2 text-emerald-700"><ShieldCheck className="h-5 w-5" /><h2 className="font-semibold">Decisión humana</h2></div>{data.decision ? <><p className="mt-4 text-lg font-semibold">{decisionLabel[data.decision.decision]}</p><p className="mt-2 text-sm leading-6 text-slate-600">{data.decision.reason}</p><p className="mt-4 text-xs text-slate-500">{data.decision.decidedBy?.fullName || "Usuario no disponible"} · {formatDate(data.decision.decidedAt)}</p></> : <><p className="mt-4 font-semibold">Aún no registrada</p><p className="mt-2 text-sm text-slate-500">Una persona responsable debe revisar evidencia, riesgos, cupos y recomendación antes de decidir.</p></>}</div>
    </section>

    {!assessment ? <Notice text="Genera primero los análisis de charla y la consolidación desde la pestaña Inteligencia." /> : ["PENDING", "PROCESSING"].includes(assessment.status) ? <Notice text="El assessment se está procesando. Puedes seguir trabajando; esta vista se actualizará automáticamente." /> : assessment.status === "STALE" ? <Notice text="Este assessment está desactualizado porque cambió una dependencia. Regenera antes de usarlo como referencia vigente." error /> : assessment.status === "FAILED" ? <Notice text={assessment.errorMessage || "El assessment falló."} error /> : output && <>
      <section className="rounded-2xl border app-card-surface p-5"><h2 className="font-semibold">Resumen consolidado</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{output.consolidatedSummary}</p><div className="mt-5 grid gap-4 lg:grid-cols-2"><ListCard title="Fortalezas" items={output.strengths} tone="green" /><ListCard title="Riesgos" items={output.risks} tone="amber" /><ListCard title="Divergencias" items={output.disagreementsBetweenInterviewers} tone="violet" /><ListCard title="Gaps de información" items={output.informationGaps} tone="slate" /></div></section>
      <section className="rounded-2xl border app-card-surface p-5"><h2 className="font-semibold">Competencias y criterios</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{output.competencies.map((item, index) => <div key={`${item.competency}-${index}`} className="rounded-xl bg-slate-50 p-4 dark:bg-white/[0.035]"><div className="flex justify-between gap-3"><p className="font-medium">{item.competency}</p><span className="text-sm font-bold text-violet-600">{item.score == null ? "N/D" : `${item.score}/100`}</span></div><p className="mt-2 text-xs leading-5 text-slate-500">{item.rationale}</p><p className="mt-2 text-[10px] text-slate-400">Confidence {Math.round(item.confidence * 100)}% · evidencia {item.evidenceRefs.join(", ") || "N/D"}</p></div>)}</div></section>
      <section className="rounded-2xl border app-card-surface p-5"><h2 className="font-semibold">Evidencia, inferencias y opiniones</h2><div className="mt-4 space-y-3">{output.evidence.map((item, index) => <div key={index} className="rounded-xl border border-slate-200 p-4 dark:border-white/10"><div className="flex flex-wrap gap-2"><Badge text={item.classification === "EVIDENCE" ? "Evidencia" : item.classification === "INFERENCE" ? "Inferencia IA" : "Opinión del entrevistador"} tone={item.classification === "EVIDENCE" ? "green" : item.classification === "INFERENCE" ? "violet" : "amber"} /><span className="text-xs text-slate-400">Referencia {item.sourceRef}</span></div><p className="mt-2 text-sm">{item.statement}</p><p className="mt-1 text-xs text-slate-500">{item.relevance}</p></div>)}</div></section>
    </>}

    <section className="rounded-2xl border app-card-surface p-5"><h2 className="font-semibold">Charlas consideradas</h2><div className="mt-4 space-y-2">{data.interviews.map((item) => <Link key={item.interview.id} to={`/interviews/${item.interview.id}`} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 dark:bg-white/[0.035]"><div className="flex items-center gap-3"><MessageSquareText className="h-4 w-4 text-slate-400" /><div><p className="text-sm font-medium">{item.interview.interviewer.fullName}</p><p className="text-xs text-slate-400">{item.interview.status} · análisis {item.analysis?.status ?? "pendiente"}</p></div></div><CheckCircle2 className={`h-4 w-4 ${item.analysis?.status === "COMPLETED" ? "text-emerald-500" : "text-slate-300"}`} /></Link>)}</div></section>

    <Modal open={decisionOpen} onClose={() => setDecisionOpen(false)} title="Registrar decisión humana" description="La recomendación IA es un insumo. Esta decisión es responsabilidad de la persona autorizada y permanece solo en CHARLAS." footer={<><Button variant="ghost" onClick={() => setDecisionOpen(false)}>Cancelar</Button><Button loading={saveDecision.isPending} disabled={reason.trim().length < 10} onClick={() => saveDecision.mutate()}>Confirmar decisión</Button></>}>
      <div className="space-y-4"><div className="rounded-xl bg-violet-50 p-4 text-sm"><p className="font-semibold">IA recomienda: {assessment ? recommendationLabel[assessment.recommendation] : "Sin recomendación"}</p><p className="mt-1 text-xs text-slate-600">Cupos locales disponibles: {data.capacity.locallyAvailable}. CORE reporta {data.capacity.pendingInCore} pendientes.</p>{output?.evidence.length ? <div className="mt-3 border-t border-violet-100 pt-3"><p className="text-[10px] font-bold uppercase tracking-wider text-violet-700">Evidencia principal a revisar</p><ul className="mt-2 space-y-1 text-xs text-slate-600">{output.evidence.slice(0, 3).map((item, index) => <li key={`${item.sourceRef}-${index}`}>• {item.statement} <span className="text-slate-400">({item.sourceRef})</span></li>)}</ul></div> : null}</div><Select label="Decisión humana" value={decision} onChange={(event) => setDecision(event.target.value as SelectionDecisionType)} options={Object.entries(decisionLabel).map(([value, label]) => ({ value, label }))} /><TextArea label="Justificación obligatoria" rows={4} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explica la evidencia y criterios considerados (mínimo 10 caracteres)." /><TextArea label="Notas opcionales" rows={3} value={notes} onChange={(event) => setNotes(event.target.value)} />{decision === "SELECTED" && data.capacity.locallySelected >= data.capacity.pendingInCore && <label className="flex gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-800"><input type="checkbox" checked={acknowledge} onChange={(event) => setAcknowledge(event.target.checked)} /><span>Confirmo que revisé la diferencia entre cupos locales y `hiredQuantity` de CORE. CHARLAS no modificará CORE.</span></label>}{saveDecision.isError && <p className="flex gap-2 text-sm text-rose-600"><AlertTriangle className="h-4 w-4 shrink-0" />{apiErrorMessage(saveDecision.error)}</p>}</div>
    </Modal>
  </div>;
}

function Badge({ text, tone }: { text: string; tone: "green" | "amber" | "red" | "violet" | "slate" }) { const styles = { green: "bg-emerald-50 text-emerald-700", amber: "bg-amber-50 text-amber-700", red: "bg-rose-50 text-rose-700", violet: "bg-violet-50 text-violet-700", slate: "bg-slate-100 text-slate-600" }; return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${styles[tone]}`}>{text}</span>; }
function ListCard({ title, items, tone }: { title: string; items: string[]; tone: "green" | "amber" | "violet" | "slate" }) { const styles = { green: "bg-emerald-50/70", amber: "bg-amber-50/70", violet: "bg-violet-50/70", slate: "bg-slate-50" }; return <div className={`rounded-xl p-4 ${styles[tone]}`}><h3 className="text-sm font-semibold">{title}</h3>{items.length ? <ul className="mt-3 space-y-2 text-sm text-slate-600">{items.map((item, index) => <li key={index}>• {item}</li>)}</ul> : <p className="mt-3 text-xs text-slate-500">Sin hallazgos.</p>}</div>; }
function Notice({ text, error = false }: { text: string; error?: boolean }) { return <div className={`rounded-2xl border p-8 text-center text-sm ${error ? "border-rose-200 bg-rose-50 text-rose-700" : "app-card-surface text-slate-500"}`}>{text}</div>; }
