import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, ArrowRightLeft, Award, Scale } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { apiErrorMessage, formatDate } from "../vacancies/formatters";
import { getIntelligenceOverview } from "./intelligenceApi";
import { recommendationLabel } from "./types";

export function ProcessComparisonPage() {
  const { processId = "" } = useParams();
  const overview = useQuery({ queryKey: ["charlas-intelligence-overview", processId], queryFn: () => getIntelligenceOverview(processId), enabled: Boolean(processId), refetchInterval: (query) => ["PENDING", "PROCESSING"].includes(query.state.data?.comparisonJob?.status ?? "") ? 2500 : false });
  if (overview.isLoading) return <Notice text="Cargando comparativo…" />;
  if (!overview.data || overview.isError) return <Notice text={apiErrorMessage(overview.error)} error />;
  const data = overview.data;
  const comparison = data.comparison;
  const refToApplication = comparison?.inputSnapshot.references ?? {};
  const comparisonCandidates = comparison?.output?.candidates ?? [];
  const cards = comparisonCandidates.map((candidate) => ({ candidate, row: data.candidates.find((item) => item.application.id === refToApplication[candidate.candidateRef]) })).filter((item) => item.row);

  return <div className="space-y-6">
    <Link to={`/charlas/vacancies/${data.process.vacancyReferenceId}`} className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-emerald-600"><ArrowLeft className="h-4 w-4" /> Volver al proceso</Link>
    <section className="rounded-2xl border app-card-surface p-5"><div className="flex items-start gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-violet-50 text-violet-600"><ArrowRightLeft className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-wider text-violet-600">Comparativo del proceso</p><h1 className="mt-1 text-3xl font-semibold">{data.process.vacancyReference.positionName}</h1><p className="mt-2 text-sm text-slate-500">{data.capacity.requestedPositions} cupos solicitados · {data.capacity.hiredInCore} contratados CORE · {data.capacity.pendingInCore} pendientes CORE</p></div></div></section>
    {!comparison ? <Notice text="El comparativo aún no ha sido generado." /> : ["PENDING", "PROCESSING"].includes(comparison.status) ? <Notice text="El comparativo se está procesando. Esta vista se actualizará automáticamente." /> : comparison.status === "FAILED" ? <Notice text={comparison.errorMessage || "El comparativo falló."} error /> : comparison.status === "STALE" ? <Notice text="Este comparativo está desactualizado porque cambió un assessment. Regenera desde la pestaña Inteligencia." error /> : comparison.output && <>
      <section className="rounded-2xl border app-card-surface p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h2 className="font-semibold">Lectura comparativa</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">{comparison.output.summary}</p></div><div className="shrink-0 text-right text-xs text-slate-400"><p>v{comparison.version} · {formatDate(comparison.generatedAt)}</p><p className="mt-1">Confidence {Math.round(comparison.output.confidence * 100)}%</p></div></div>{!comparison.isScoreComparable && <p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">No se muestra ranking: los candidatos no tienen cobertura y scoring suficientemente comparables.</p>}</section>
      {comparison.ranking && <section className="rounded-2xl border border-violet-200 bg-violet-50/50 p-5"><div className="flex items-center gap-2 text-violet-700"><Award className="h-5 w-5" /><h2 className="font-semibold">Orden por score comparable</h2></div><p className="mt-1 text-xs text-slate-500">Este orden no selecciona candidatos y no limita la decisión a un solo cupo.</p><div className="mt-4 flex flex-wrap gap-3">{comparison.ranking.map((item) => { const row = data.candidates.find((candidate) => candidate.application.id === item.applicationId); return <div key={item.applicationId} className="rounded-xl bg-white p-4 shadow-sm dark:bg-black/10"><p className="text-xs font-bold text-violet-600">#{item.rank}</p><p className="mt-1 font-semibold">{row?.application.candidate.fullName || "Candidato"}</p><p className="mt-1 text-sm">{item.score.toFixed(1)} / 100</p></div>; })}</div></section>}
      <section className="grid gap-4 xl:grid-cols-2">{cards.map(({ candidate, row }) => <article key={candidate.candidateRef} className="rounded-2xl border app-card-surface p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{candidate.candidateRef}</p><h2 className="mt-1 text-xl font-semibold">{row!.application.candidate.fullName}</h2><p className="mt-1 text-xs text-slate-500">Cobertura {row!.coverage.completedInterviews}/{row!.coverage.requiredInterviews}</p></div><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-semibold text-violet-700">{row!.assessment ? recommendationLabel[row!.assessment.recommendation] : "Sin assessment"}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Column title="Fortalezas diferenciales" items={candidate.strengths} tone="green" /><Column title="Riesgos diferenciales" items={candidate.risks} tone="amber" /><Column title="Competencias" items={candidate.competencies} tone="violet" /><Column title="Gaps" items={candidate.gaps} tone="slate" /></div><div className="mt-4 rounded-xl border border-slate-200 p-3 text-sm dark:border-white/10"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Trade-offs</p><ul className="mt-2 space-y-1 text-xs text-slate-600">{candidate.tradeOffs.map((item, index) => <li key={index}>• {item}</li>)}</ul><p className="mt-3 text-sm">{candidate.recommendationSummary}</p></div><Link to={`/charlas/applications/${row!.application.id}/intelligence`} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-emerald-600">Ver evidencia y decisión <Scale className="h-4 w-4" /></Link></article>)}</section>
      <section className="grid gap-4 lg:grid-cols-2"><Column title="Trade-offs entre candidatos" items={comparison.output.crossCandidateTradeOffs} tone="violet" /><Column title="Gaps del comparativo" items={comparison.output.informationGaps} tone="slate" /></section>
      <section className="rounded-2xl border border-emerald-200 bg-emerald-50/60 p-5"><h2 className="font-semibold text-emerald-800">Resumen de recomendación IA</h2><p className="mt-3 text-sm leading-7 text-slate-700">{comparison.output.recommendationSummary}</p><p className="mt-4 text-xs font-semibold text-emerald-800">La IA recomienda. Las personas responsables deciden individualmente y pueden seleccionar hasta los cupos correspondientes.</p></section>
    </>}
  </div>;
}

function Column({ title, items, tone }: { title: string; items: string[]; tone: "green" | "amber" | "violet" | "slate" }) { const styles = { green: "bg-emerald-50/70", amber: "bg-amber-50/70", violet: "bg-violet-50/70", slate: "bg-slate-50" }; return <div className={`rounded-xl p-4 ${styles[tone]}`}><h3 className="text-xs font-bold uppercase tracking-wider">{title}</h3>{items.length ? <ul className="mt-3 space-y-2 text-sm text-slate-600">{items.map((item, index) => <li key={index}>• {item}</li>)}</ul> : <p className="mt-3 text-xs text-slate-500">Sin hallazgos.</p>}</div>; }
function Notice({ text, error = false }: { text: string; error?: boolean }) { return <div className={`rounded-2xl border p-10 text-center text-sm ${error ? "border-rose-200 bg-rose-50 text-rose-700" : "app-card-surface text-slate-500"}`}>{text}</div>; }
